src/api/urls.py
from django.urls import path
from . import views


app_name = 'api'

urlpatterns = [
    path('home/', views.home_api, name='home_api'),
    path('empleados/', views.ListaEmpleados.as_view(), name='lista_empleados'),
    path('empleados/<int:pk>/', views.DetalleEmpleado.as_view(),
         name='detalle_empleado'),
    path('coordinadores/', views.ListaCoordinadores.as_view(),
         name='lista_coordinadores'),
    path('coordinadores/<int:pk>/', views.DetalleCoordinadores.as_view(),
         name='detalle_coordinadores'),
    path('servicios/', views.ListaServicios.as_view(), name='lista_servicios'),
    path('servicios/<int:pk>/', views.DetalleServicios.as_view(),
         name='detalle_servicios'),
    path('reservas_servicios/', views.ListaReservaServicios.as_view(),
         name='lista_reservas_servicios'),
    path('reservas_servicios/<int:pk>/', views.DetalleReservaServicios.as_view(),
         name='detalle_reservas_servicios'),
    path('clientes/', views.ListaClientes.as_view(), name='lista_clientes'),
    path('clientes/<int:pk>/', views.DetalleClientes.as_view(),
         name='detalle_clientes'),

]

src/app_clientes/urls.py
from django.urls import path
from . import views
# from .views import desactivar_cliente

app_name = 'clientes'

urlpatterns = [
    path('nuevo/', views.ClienteCreateView.as_view(), name='crear'),
    path('listar/', views.ClienteListView.as_view(), name='listar'),
    path('detalle/<int:pk>/', views.ClienteDetailView.as_view(), name='detalle'),
    path('modificar/<int:pk>/', views.ClienteUpdateView.as_view(), name='modificar'),
    path('desactivar/<int:pk>/', views.desactivar_cliente, name='desactivar'),
    path('activar/<int:pk>/', views.activar_cliente, name='activar'),
]

src/app_coordinadores/urls.py
from . import views
from django.urls import path
from .views import activar_coordinador

# NAME SPACE de la url de la app.
app_name = "coordinadores"

urlpatterns = [

    path('listar/', views.CoordinadorListView.as_view(), name='listar'),
    path('modificar/<int:pk>/',
         views.CoordinadorUpdateView.as_view(), name='modificar'),
    path('nuevo/', views.CoordinadorCreateView.as_view(), name='nuevo'),
    # path('desactivar/<int:pk>/',
    #      views.CoordinadorDesactivateView.as_view(), name='desactivar'),
    path('desactivar/<int:pk>/', views.desactivar_coordinador, name='desactivar'),
    path('activar/<int:pk>/', views.activar_coordinador, name='activar'),
]

src/app_empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados'

urlpatterns = [
    path('listar/', views.EmpleadoListView.as_view(), name='listar'),
    path('nuevo/', views.EmpleadoCreateView.as_view(), name='nuevo'),
    path('modificar/<int:pk>/', views.EmpleadoUpdateView.as_view(), name='modificar'),
    path('desactivar/<int:pk>/', views.desactivar_empleado, name='desactivar'),
    path('activar/<int:pk>/', views.activar_empleado, name='activar'),
]

src/app_servicio/urls.py
from django.urls import path
from . import views

app_name = 'servicios'


urlpatterns = [
    path('nuevo/', views.ServicioCreateView.as_view(), name='nuevo'),
    path('listar/', views.ServicioListView.as_view(), name='listar'),
    path('detalle/<int:pk>/', views.ServicioDetailView.as_view(), name='detalle'),
    path('modificar/<int:pk>/', views.ServicioUpdateView.as_view(), name='modificar'),
    path('activar/<int:pk>/', views.activar_servicio, name='activar'),
    path('desactivar/<int:pk>/', views.desactivar_servicio, name='desactivar'),
]

src/django_eventos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coordinadores/', include('app_coordinadores.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('empleados/', include('app_empleados.urls')),
    path('reservas_servicios/', include('app_reservas_servicios.urls')),
    path('servicios/', include('app_servicio.urls')),
    path('api/', include('api.urls')),
    path('', include('app_reservas.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/api/models.py
from django.db import models

# Create your models here.

# class Empleado(models.Model):
#     nombre = models.CharField(max_length=255)
    

src/api/views.py
from django.shortcuts import render
from rest_framework import generics
from app_empleados.models import Empleado
from app_coordinadores.models import Coordinador
from app_servicio.models import Servicio
from app_clientes.models import Cliente
from app_reservas_servicios.models import ReservaServicio
from .serializers import EmpleadoSerializer, EmpleadoSerializerList, CoordinadorSerializerList, CoordinadorSerializer
from .serializers import ReservaServicioSerializerList, ReservaServicioSerializer, ServicioSerializer, ServicioSerializerList
from .serializers import ClienteSerializerList, ClienteSerializer
# Create your views here.

# EMPLEADOS

def home_api(request):
    return render(request, 'home_api.html')

class ListaEmpleados(generics.ListAPIView):

    queryset = Empleado.objects.all()
    serializer_class = EmpleadoSerializerList


class DetalleEmpleado(generics.RetrieveAPIView):
    
    
    queryset = Empleado.objects.all()
    serializer_class = EmpleadoSerializer

# COORDINADORES


class ListaCoordinadores(generics.ListAPIView):
    queryset = Coordinador.objects.all()
    serializer_class = CoordinadorSerializerList


class DetalleCoordinadores(generics.RetrieveAPIView):
    queryset = Coordinador.objects.all()
    serializer_class = CoordinadorSerializer

# SERVICIOS


class ListaServicios(generics.ListAPIView):
    queryset = Servicio.objects.all()
    serializer_class = ServicioSerializerList


class DetalleServicios(generics.RetrieveAPIView):
    queryset = Servicio.objects.all()
    serializer_class = ServicioSerializer


# Reserva Servicio

class ListaReservaServicios(generics.ListAPIView):
    queryset = ReservaServicio.objects.all()
    serializer_class = ReservaServicioSerializerList


class DetalleReservaServicios(generics.RetrieveAPIView):
    queryset = ReservaServicio.objects.all()
    serializer_class = ReservaServicioSerializer

class ListaClientes(generics.ListAPIView):
    queryset = Cliente.objects.all()
    serializer_class = ClienteSerializerList


class DetalleClientes(generics.RetrieveAPIView):
    queryset = Cliente.objects.all()
    serializer_class = ClienteSerializer

src/templates/api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Api de servicios</title>
</head>
<body>
    
</body>
</html>

src/templates/base.html
<!doctype html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block titulo %}
      {% endblock titulo %}
    </title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  </head>
  <body>
    <div class= "container-fluid">
      <nav class="navbar sticky-top navbar-expand-md bg-body-tertiary"  style="width: 100%">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Inicio</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'reserva_servicios:listar' %}">Reservas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'clientes:listar' %}">Clientes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'empleados:listar' %}">Empleados</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'coordinadores:listar' %}">Coordinadores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'servicios:listar' %}">Servicios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/api/home">Api</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      <div class ="container">
        {% block contenido %}
        {% endblock contenido %}
      </div>
    
    <div style="position: relative; min-height: 50vh;"> 
      <footer class="bg-dark text-center text-white" style="position:absolute; bottom: 0; width: 100%;">
          <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2023 Copyright: ALkemy - Squat 2
        </div>
          <!-- Copyright -->
      </footer>
    </div> 
    </div>
    
<!-- End of .container -->
    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}


{% block titulo %}  Home  {% endblock %}

{% block contenido %}
    <div class= "custom-container">
        <header>
            <a href="{% url 'reserva_servicios:nuevo' %}">Reservá Tus Servicios</a>
        </header>
        <article>
        <h3>Clientes</h3>
        <section class="d-flex justify-content-center">
            <a href="{% url 'clientes:listar' %}">Listado de Clientes</a>
        </section>
        </article>
        <article>
        <h3>Empleados</h3>
        <section class="d-flex justify-content-center">
            <a href="{% url 'empleados:listar' %}">Listado de Empleados</a>
        </section>
        </article>
        <article>
        <h3>Coordinadores</h3>
        <section class="d-flex justify-content-center">
            <a href="{% url 'coordinadores:listar' %}">Listado de Coordinadores</a>
        </section>
        </article>
        <article>
        <h3>Servicios</h3>
        <section class="d-flex justify-content-center">
            <a href="{% url 'servicios:listar' %}">Listado de Servicios</a>
        </section>
        </article>
    </div>
{% endblock contenido %}

src/templates/home_api.html
{% extends "base.html" %}

{% block titulo %}  Home API {% endblock %}

{% block contenido %}
<br>

<h1 style="color:white">API RESERVAS</h1>

<h2 style="color:white">Listado de endpoints: </h2> 

<table class="table">
  <thead>
    <tr>
      <th>Petición</th>
      <th>URL</th>
      <th>Descripción</th>
     
     
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>GET</td> 
        <td><a href="{% url 'api:lista_empleados' %}">Listado de empleados</a> </td>
        <td>Retorna el listado de datos de todos los empleados activos</td> 
        
    </tr>
    <tr>
        <td>GET</td> 
        <td><a href="{% url 'api:lista_coordinadores' %}">Listado de coordinadores</a> </td>
        <td>Retorna el listado de datos de todos los coordinadores activos</td> 
        
    </tr>
      
    <tr>
        <td>GET</td> 
        <td><a href="{% url 'api:lista_servicios' %}">Listado de servicios</a> </td>
        <td>Retorna el listado de datos de todos los servicios activos que posee la empresa</td>

    </tr>
      
    <tr>
        <td>GET</td> 
        <td><a href="{% url 'api:lista_reservas_servicios' %}">Listado de reservas servicios</a> </td>
        <td>Retorna el listado de las reservas realizadas por los clientes</td> 
        
    </tr>
    
    </td>
    
  </tbody>
</table>
<br>
<br>


<div class="card text-center">
  <div class="card-header"  >
    API RESERVAS
  </div>
  <div class="card-body">
    <h4 class="card-title">Prueba ahora!</h4>
    <p class="card-text">Necesitas ayuda? Prueba con el número de ID que quieras ver en detalle. Por ejemplo: servicios/1, empleados/2, coordinadores/3, reservas_servicios/1</p>
    <div class="container">
      <script>
          function abrir(){
              let url = document.getElementById("url").value;
              urlNueva = "http://localhost:8000/api/" + url
            
              window.open(urlNueva)
          }
      </script>
      <div class= "container-fluid" style="font-size:1.3rem">
      <label for="url">
        http://localhost:8000/api/
      <input id="url" type="url">
      </div>
      <br>
      <div class="d-grid gap-2" style="width: 40rem align-item:center">
      <button onclick="abrir()" class="btn btn-primary ">ABRIR</button>
      </div>
</div>
  </div>
  <div class="card-footer text-muted">
  Prueba de servicios Reservas API RESTFul
  </div>
</div>
<br> <br>
<p style="color:white">Esta es una API solo de consumo: solo el método HTTP GET está disponible en los recursos.<p>
  <h6>Status code</h6>
<ul>
  <li style="color:white">200 OK: El código de respuesta de estado de éxito HTTP 200 OK indica que la solicitud ha tenido éxito. </li>
  <li style="color:white">404: El código de estado de respuesta HTTP 404 Not Found indica que el servidor no puede encontrar el recurso solicitado.</li>
  <li style="color:white">500: El código de respuesta de error del servidor interno HTTP 500 indica que el servidor encontró una condición inesperada que le impedía cumplir la solicitud.</li>
</ul>
<br>
<div>
  
<h3 style="color:white">Endpoints:</h3>
<div style="display:flex justify-content:center">
  <button type="button" class="btn btn-lg btn-primary" data-bs-toggle="popover" title="Métodos HTTP permitidos" >GET</button>
  <h4 style="color:white">http://localhost:8000/api/coordinadores</h4>

</div>
  
  <h6 style="color:white"> Retorna el listado de datos de todos los coordinadores activos e inactivos </h6>
</div>
<br>
<div class="card border-dark mb-3" style="max-width: 40rem;">
  
  <div class="card-body text-dark">
    <p class="card-text">
      <code>
      HTTP 200 OK <br>
      Allow: GET, HEAD, OPTIONS <br>
      Content-Type: application/json <br>
      Vary: Accept <br>
          { <br>
              "id": 1, <br>
              "nombre": "Kevin" <br>
          }, <br>
          { <br>
              "id": 2, <br>
              "nombre": "Camila" <br>
          } <br>
      
        </code>
      </p>
  </div>
</div>
<div style="display:flex justify-content:center">
  <button type="button" class="btn btn-lg btn-primary" data-bs-toggle="popover" title="Métodos HTTP permitidos" >GET</button>
  <h4 style="color:white">http://localhost:8000/api/coordinadores/id</h4>

</div>
<h6 style="color:white"> Retorna el detalle de datos del coordinador que coincida con el ID ingresado </h6>
<br>
<div class="card border-dark mb-3" style="max-width: 40rem;">
  
  <div class="card-body text-dark">
    <p class="card-text">
      <code>
      HTTP 200 OK <br>
      Allow: GET, HEAD, OPTIONS <br>
      Content-Type: application/json <br>
      Vary: Accept <br>
         
      {<br>
        "id": 1, <br>
        "nombre": "Kevin", <br>
        "apellido": "McCallister", <br>
        "documento": 31151345, <br>
        "fecha_alta": "2023-12-12T00:00:00Z", <br>
        "activo": true <br>
    } <br>
        </code>
      </p>
  </div>
</div>



{% endblock contenido %}