src/api/urls.py
from django.urls import path
from . import views


app_name = 'api'

urlpatterns = [
    path('home/', views.home_api, name='home_api'),
    path('empleados/', views.ListaEmpleados.as_view(), name='lista_empleados'),
    path('empleados/<int:pk>/', views.DetalleEmpleado.as_view(),
         name='detalle_empleado'),
    path('coordinadores/', views.ListaCoordinadores.as_view(),
         name='lista_coordinadores'),
    path('coordinadores/<int:pk>/', views.DetalleCoordinadores.as_view(),
         name='detalle_coordinadores'),
    path('servicios/', views.ListaServicios.as_view(), name='lista_servicios'),
    path('servicios/<int:pk>/', views.DetalleServicios.as_view(),
         name='detalle_servicios'),
    path('reservas_servicios/', views.ListaReservaServicios.as_view(),
         name='lista_reservas_servicios'),
    path('reservas_servicios/<int:pk>/', views.DetalleReservaServicios.as_view(),
         name='detalle_reservas_servicios'),
    path('clientes/', views.ListaClientes.as_view(), name='lista_clientes'),
    path('clientes/<int:pk>/', views.DetalleClientes.as_view(),
         name='detalle_clientes'),

]

src/app_clientes/urls.py
from django.urls import path
from . import views
# from .views import desactivar_cliente

app_name = 'clientes'

urlpatterns = [
    path('nuevo/', views.ClienteCreateView.as_view(), name='crear'),
    path('listar/', views.ClienteListView.as_view(), name='listar'),
    path('detalle/<int:pk>/', views.ClienteDetailView.as_view(), name='detalle'),
    path('modificar/<int:pk>/', views.ClienteUpdateView.as_view(), name='modificar'),
    path('desactivar/<int:pk>/', views.desactivar_cliente, name='desactivar'),
    path('activar/<int:pk>/', views.activar_cliente, name='activar'),
]

src/django_eventos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coordinadores/', include('app_coordinadores.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('empleados/', include('app_empleados.urls')),
    path('reservas_servicios/', include('app_reservas_servicios.urls')),
    path('servicios/', include('app_servicio.urls')),
    path('api/', include('api.urls')),
    path('', include('app_reservas.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/clientes/crear_cliente.html
{% extends "base.html" %}

{% block titulo %}
    {{titulo}}
{% endblock titulo %}

{% block contenido %}
<div class="container pt-3  " style="width: 50rem">
    <div class="card " style=" d-flex justify-content-center width: 38rem; border-radius: 1.5rem;">
        <div class="card-body" >
          <h5 class="card-title" style= "text-align: center">{{titulo}}</h5>
          <p class="card-text">
            <form action="" method="POST" enctype="multipart/form-data"  class="form-group mb-3">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for = '{{ form.nombre.id_for_label }}'>{{form.nombre.html_name|capfirst}}</label>
                    <input type="{{form.nombre.html_name}}" class="form-control" id="nombre"  name="{{form.nombre.html_name}}"  required>
                    <small class="form-text text-muted">{{form.nombre.help_text}}</small>
                </div>
                <div class="form-group mb-3">
                    <label for = '{{ form.apellido.id_for_label }}'>{{ form.apellido.html_name|capfirst}}</label>
                    <input type="{{ form.apellido.html_name}}" class="form-control" id="apellido"  name="{{ form.apellido.html_name}}"required>
                    <small class="form-text text-muted">{{ form.apellido.help_text}}</small>
                </div>

                <div class="form-group form-switch">
                    <input class="form-check-input" type="checkbox" class="form-control" id="activo"  name="{{ form.activo.html_name}}" value="true" checked >
                    <label for = '{{ form.activo.id_for_label }}'>{{ form.activo.html_name|capfirst}} </label>
                    <small class="form-text text-muted">{{ form.activo.help_text}}</small>
                </div>
                <br>
                <div class="d-grid gap-2">
                    <a class = "btn btn-warning " href="{% url 'clientes:listar' %}">Volver</a>
                    <button class = "btn btn-primary " type="submit">{{mensaje_boton}}</button>
                </div>
            </form>
          </p>
        </div>
    </div>
</div>
{% endblock contenido %}

src/templates/clientes/detalle_cliente.html
{% extends "base.html" %}

{% block titulo %}
DETALLES DEL CLIENTE
{% endblock titulo %}

{% block contenido %}

<h1>{{cliente}}</h1>

<div class="alert alert-primary" role="alert">
    Volver a la lista - <a href="{% url 'clientes:listar'%}">Click aquí</a>
  </div>

{% endblock contenido %}

src/templates/clientes/listar_cliente.html
{% extends 'base.html' %} 
​
{% block titulo %}
lista clientes 
{% endblock titulo %}
|
{% block contenido %}

{% for msg in messages%}

  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{msg}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor%}

<h2 class="text-center my-2" style="color:white">Lista de clientes: </h2> 
​<a class="btn btn-success"  href= "{% url 'clientes:crear'%}">Agregar un nuevo cliente</a>
<table class="table table-striped table-hover table-secondary my-3">
  <thead>
    <tr>
      <th>#</th>
      <th>Apellido</th>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
    <tr>
      <th scope="row">
        <a href= "{{ cliente.get_absolute_url }}">
        {{cliente.pk}}
        </a>
      </th>
      <td>{{ cliente.apellido }}</td>
      <td>{{ cliente.nombre }}</td>
      <td>
        <a class="btn btn-warning" href="{% url 'clientes:modificar' pk=cliente.id %}">Editar</a>
        {% if cliente.activo  %}
          <a class="btn btn-danger" href= "{% url 'clientes:desactivar' pk=cliente.pk%}"> Desactivar </a>
        {% else %}
         <a class="btn btn-primary" href= "{% url 'clientes:activar' pk=cliente.pk%}">  Activar</a>
       {% endif %}
    </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock contenido %}

src/templates/clientes/modificar_cliente.html
{% extends "base.html" %}

{% block titulo %}
    {{titulo}}
{% endblock titulo %}

{% block contenido %}

<div class="container pt-3  " style="width: 50rem">
    <div class="card " style=" d-flex justify-content-center width: 38rem; border-radius: 1.5rem;">
        <div class="card-body" >
          <h5 class="card-title" style= "text-align: center">{{ titulo }}</h5>
          <p class="card-text">
            <form action="" method="POST" enctype="multipart/form-data"  class="input-group flex-column">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for = '{{ form.nombre.id_for_label }}'>{{form.nombre.html_name|capfirst}}</label>
                    <input type="{{form.nombre.html_name}}" class="form-control" id="nombre"  name="{{form.nombre.html_name}}" value="{{form.nombre.value}}" placeholder="Nombre del Cliente" required>
                    <small class="form-text text-muted">{{form.nombre.help_text}}</small>
                </div>
                <div class="form-group mb-3">
                    <label for = '{{ form.apellido.id_for_label }}'>{{ form.apellido.html_name|capfirst}}</label>
                    <input type="{{ form.apellido.html_name}}" class="form-control" id="apellido"  name="{{ form.apellido.html_name}}" value="{{form.apellido.value}}" placeholder="Apellido del Cliente" required>
                    <small class="form-text text-muted">{{ form.apellido.help_text}}</small>
                </div>

                <div class="form-group form-switch">
                    <input class="form-check-input" type="checkbox" class="form-control" id="activo"  name="{{ form.activo.html_name}}" value="{{form.activo.value}}" checked >
                    <label for = '{{ form.activo.id_for_label }}'>{{ form.activo.html_name|capfirst}} </label>
                    <small class="form-text text-muted">{{ form.activo.help_text}}</small>
                </div>
                <br>
                <div class="d-grid gap-2">
                    <a class = "btn btn-warning " href="{% url 'clientes:listar' %}">Volver</a>
                    <button class = "btn btn-primary " type="submit">{{mensaje_boton}}</button>
                </div>
            </form>
          </p>
        </div>
    </div>
</div>
{% endblock contenido %}